import { GLOBALS, type WorldState, type Agent, type Position } from './types';
import { calculateUtility, derivePreferenceParams } from './math';
import { generateRandomId } from './init';
import { generateOrders, resolveMarket } from './market';

/**
 * Increments food on green squares by 1 (up to MAX_FOOD_PER_BLOCK).
 * Gold squares remain unchanged.
 */
export const updateEnvironment = (grid: WorldState['grid']): WorldState['grid'] => {
  return grid.map(row => 
    row.map(sq => {
      if (sq.type === 'Food') {
        return {
          ...sq,
          foodResources: Math.min(GLOBALS.MAX_FOOD_PER_BLOCK, sq.foodResources + GLOBALS.FOOD_GROWTH_RATE)
        };
      }
      return sq;
    })
  );
};

const getAdjacentPositions = (pos: Position, gridWidth: number, gridHeight: number): Position[] => {
  const adjs: Position[] = [];
  if (pos.x > 0) adjs.push({ x: pos.x - 1, y: pos.y });
  if (pos.x < gridWidth - 1) adjs.push({ x: pos.x + 1, y: pos.y });
  if (pos.y > 0) adjs.push({ x: pos.x, y: pos.y - 1 });
  if (pos.y < gridHeight - 1) adjs.push({ x: pos.x, y: pos.y + 1 });
  return adjs;
};


/**
 * Decides whether an agent should Exploit (harvest) or Explore (move).
 * Calculates expected utility of actions based on preference parameters.
 * IMPORTANT: It now accepts the `expectedExploitDeltas` generated by the tick loop
 * to evaluate the decision fairly when N agents occupy the same tile.
 */
export const resolveAgentDecision = (agent: Agent, expectedExploitDeltas: {dF: number, dG: number}): { choice: 'Exploit' | 'Explore' } => {
  const params = derivePreferenceParams(agent);
  const currentUtility = calculateUtility(agent.foodInventory, agent.goldInventory, params);
  
  const exploitUtility = calculateUtility(agent.foodInventory + expectedExploitDeltas.dF, agent.goldInventory + expectedExploitDeltas.dG, params);
  
  const expectedExploreDeltas = { dF: 0.5, dG: 0.1 }; // small expected find
  const exploreUtility = calculateUtility(agent.foodInventory + expectedExploreDeltas.dF, agent.goldInventory + expectedExploreDeltas.dG, params);
  
  const exploitMarginal = exploitUtility - currentUtility;
  const exploreMarginal = exploreUtility - currentUtility;
  
  if (exploitMarginal > exploreMarginal && exploitMarginal > 0) {
    return { choice: 'Exploit' };
  } else {
    return { choice: 'Explore' };
  }
};

/**
 * Pure reducer function mapping WorldState to exactly the next WorldState.
 */
export const tick = (prevState: WorldState, options: { marketsEnabled: boolean } = { marketsEnabled: false }): WorldState => {
  // First, Environment naturally updates (food grows)
  let nextGrid = updateEnvironment(prevState.grid).map(row => [...row]);
  
  // Then Agents take turns.
  // To evaluate Fair Distribution, we iterate sequentially but process agents by TILE rather than strictly by agent age.
  
  // Group all LIVING agents by their XY tile
  const livingAgentsByPosition = prevState.agents.reduce((acc, agent) => {
    if (agent.isDead) return acc;
    const key = `${agent.pos.x},${agent.pos.y}`;
    if (!acc[key]) acc[key] = [];
    acc[key].push(agent);
    return acc;
  }, {} as Record<string, Agent[]>);
  
  const resolvedLivingAgents: Agent[] = [];

  // Resolve actions tile by tile
  Object.values(livingAgentsByPosition).forEach(occupants => {
    const pos = occupants[0].pos;
    const sq = nextGrid[pos.y][pos.x];
    
    // 1. Determine baseline available resources on this tile
    // Food is entirely available to be extracted wherever it is.
    const totalAvailF = sq.foodResources;
    
    // 2. Determine Expected fractional resources perfectly evenly spread across all occupants
    const N = occupants.length;
    
    // Gold is entirely available to be picked up if it's sitting on Dirt or Food.
    // If it's a Gold tile, it's trapped in a mine, so they can extract up to N per turn 
    // collaboratively (bounded by the amount of gold actually in the mine).
    const totalAvailG = sq.type === 'Gold' ? Math.min(N, sq.goldResources) : sq.goldResources;
    
    // (If 10 agents are on a 5-food tile, everyone expects 0.5 food before deciding).
    const expectedDeltas = {
      dF: totalAvailF / N,
      dG: totalAvailG / N,
    };
    
    // 3. Poll each occupant using their identical fractional expectation
    const exploitingAgents: Agent[] = [];
    const exploringAgents: Agent[] = [];
    
    occupants.forEach(a => {
      const decision = resolveAgentDecision(a, expectedDeltas);
      if (decision.choice === 'Exploit') {
        exploitingAgents.push(a);
      } else {
        exploringAgents.push(a);
      }
    });
    
    // 4. Given M actual exploiters, calculate REAL fractional resources extracted and update grid.
    const M = exploitingAgents.length;
    let actualDfPerAgent = 0;
    let actualDgPerAgent = 0;
    
    if (M > 0) {
      // Extract from map securely using Math.min against available
      const totalExtractedF = Math.min(totalAvailF, M * expectedDeltas.dF); // If everyone exploits, they extract all `totalAvailF`, bounded
      const totalExtractedG = Math.min(totalAvailG, M * expectedDeltas.dG);
      
      // M agents split exactly the newly extracted pie
      actualDfPerAgent = totalExtractedF / M;
      actualDgPerAgent = totalExtractedG / M;
      
      nextGrid[pos.y][pos.x] = {
        ...sq,
        foodResources: Math.max(0, sq.foodResources - totalExtractedF),
        goldResources: Math.max(0, sq.goldResources - totalExtractedG),
      };
    }
    
    // 5. Apply states
    
    // Explorers just move
    exploringAgents.forEach(explAgent => {
      const adjs = getAdjacentPositions(explAgent.pos, nextGrid[0].length, nextGrid.length);
      const randomAdj = adjs[Math.floor(Math.random() * adjs.length)];
      
      resolvedLivingAgents.push({
        ...explAgent,
        pos: randomAdj
      });
    });
    
    // Exploiters eat/gain gold, staying in place
    exploitingAgents.forEach(expAgent => {
      let newHunger = expAgent.currHunger;
      let storedFood = expAgent.foodInventory + actualDfPerAgent; // Usually fractional, but Math is valid
      
      // Satisfy hunger loop (since they exploited food)
      if (actualDfPerAgent > 0) {
        while (newHunger > 0 && storedFood >= GLOBALS.FOOD_CONSUMPTION_RATE) {
          storedFood -= GLOBALS.FOOD_CONSUMPTION_RATE;
          newHunger = Math.max(0, newHunger - GLOBALS.FOOD_CONSUMPTION_RATE);
        }
      }

      resolvedLivingAgents.push({
        ...expAgent,
        currHunger: newHunger,
        foodInventory: storedFood,
        goldInventory: expAgent.goldInventory + actualDgPerAgent
      });
    });
  });
  
  // Re-merge all dead agents back in unaffected
  const deadAgents = prevState.agents.filter(a => a.isDead);
  const allResolvedAgents = [...resolvedLivingAgents, ...deadAgents];

  // 6. Loop over allResolvedAgents to apply per-tick hunger increment & death
  const nextAgents = allResolvedAgents.map(agent => {
    // Dead agents stay dead
    if (agent.isDead) return agent;
    
    // Apply per-tick rule: Consume 1 food OR increment hunger
    let finalFood = agent.foodInventory;
    let finalHunger = agent.currHunger;
    
    if (finalFood >= GLOBALS.FOOD_CONSUMPTION_RATE) {
      finalFood -= GLOBALS.FOOD_CONSUMPTION_RATE;
      finalHunger = Math.max(0, finalHunger - 1);
    } else {
      // No food to eat!
      finalHunger += GLOBALS.HUNGER_ACCUMULATED_PER_TURN;
    }
    
    // Check death
    const shouldDie = finalHunger >= GLOBALS.DEATH_AT_HUNGER;
    
    if (shouldDie && agent.goldInventory > 0) {
      // Drop gold on current tile
      const sq = nextGrid[agent.pos.y][agent.pos.x];
      nextGrid[agent.pos.y][agent.pos.x] = {
        ...sq,
        goldResources: sq.goldResources + agent.goldInventory
      };
    }
    
    return {
      ...agent,
      foodInventory: finalFood,
      currHunger: finalHunger,
      isDead: shouldDie,
      diedOnTurn: shouldDie ? prevState.tick + 1 : undefined,
    };
  });
  
  // Reproduction Logic: Group living agents by their active tile
  // If exactly 2 living agents are on a Dirt tile, spawn a baby.
  const agentsByPosition = nextAgents.reduce((acc, agent) => {
    if (agent.isDead) return acc;
    const key = `${agent.pos.x},${agent.pos.y}`;
    if (!acc[key]) acc[key] = [];
    acc[key].push(agent);
    return acc;
  }, {} as Record<string, Agent[]>);
  
  const babies: Agent[] = [];
  
  Object.values(agentsByPosition).forEach(occupants => {
    // Only agents less than max pregnancy hunger can participate in copulation
    const fertileOccupants = occupants.filter(a => a.currHunger < GLOBALS.MAX_PREGNANCY_HUNGER);
    if (fertileOccupants.length >= 2) {
      const pos = fertileOccupants[0].pos;
      if (nextGrid[pos.y][pos.x].type === 'Dirt' && Math.random() < GLOBALS.REPRODUCE_PERCENT_CHANCE) {
        // Spawn exactly 1 baby if there are >= 2 fertile agents here and they pass the chance check.
        babies.push({
          id: generateRandomId(),
          pos: pos,
          currHunger: GLOBALS.STARTING_AGENT_BABY_HUNGER,
          baseGreed: Math.random() * 3, // Initial random greed
          foodInventory: 0,
          goldInventory: 0,
          bornOnTurn: prevState.tick + 1,
          color: `hsl(${Math.floor(Math.random() * 360)}, 70%, 50%)`,
        });

        // Inflict the birthing cost on the two parents that copulated
        (fertileOccupants[0] as any).currHunger += GLOBALS.BIRTHING_HUNGER_COST;
        (fertileOccupants[1] as any).currHunger += GLOBALS.BIRTHING_HUNGER_COST;
      }
    }
  });

  let finalAgents = [...nextAgents, ...babies];
  let nextMarketState = prevState.market;

  // --- MARKET RESOLUTION ---
  if (options.marketsEnabled) {
    const { bids, asks } = generateOrders(finalAgents);
    const { updatedAgents, marketState } = resolveMarket(bids, asks, finalAgents, prevState.tick + 1);
    finalAgents = updatedAgents;
    nextMarketState = marketState;
  } else {
    // Wipe if disabled
    nextMarketState = {
      bids: [],
      asks: [],
      lastClearingPrice: null,
      volumeLastTick: 0,
      tradesLastTick: []
    };
  }

  return {
    tick: prevState.tick + 1,
    grid: nextGrid,
    agents: finalAgents,
    market: nextMarketState
  };
};
